# GitHub Pages に Jekyll サイトを自動デプロイするワークフロー

name: Deploy Jekyll with GitHub Pages dependencies preinstalled

# このワークフローを実行するタイミング
on:
  push:
    # デフォルトブランチに push されたときに実行
    branches: ["main"]
  workflow_dispatch:
    # Actions タブから手動で実行可能にする

# GITHUB_TOKEN に付与する権限
permissions:
  contents: read   # リポジトリの内容を読み取る権限
  pages: write     # GitHub Pages へのデプロイ権限
  id-token: write  # 環境への認証トークン生成に必要

# 同時に複数のデプロイを制御
concurrency:
  group: "pages"            # 同じグループ名のワークフローは1つずつ実行
  cancel-in-progress: false # 実行中のジョブはキャンセルせず待機

jobs:
  # ========================================
  # 1. Build Job: Jekyll サイトをビルド
  # ========================================
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout # リポジトリのコードをチェックアウト
        uses: actions/checkout@v4

      - name: Setup Ruby # Ruby 3.4 環境をセットアップし、Bundler キャッシュを有効化
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3' # ローカルと同じバージョンにする
          bundler-cache: true

      - name: Install dependencies # Gemfile の内容を元に Jekyll とプラグインをインストール
        run: |
          gem install bundler
          bundle install

      - name: Build with Jekyll # Jekyll サイトをビルドして _site に出力
        run: bundle exec jekyll build

      - name: Upload artifact # GitHub Pages にデプロイするために _site をアップロード
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site

  # ========================================
  # 2. Deploy Job: GitHub Pages にデプロイ
  # ========================================
  deploy:
    environment:
      name: github-pages # GitHub Pages 環境名
      url: ${{ steps.deployment.outputs.page_url }} # 公開 URL を取得
    runs-on: ubuntu-latest
    needs: build # build ジョブが完了するまで待機
    steps:
      - name: Deploy to GitHub Pages # _site の内容を GitHub Pages にデプロイ
        id: deployment
        uses: actions/deploy-pages@v4